name: Test

on:
  push:
    branches:
      - master
      - renovate/**
  pull_request:
  merge_group:
  # `workflow_dispatch` allows CodSpeed to trigger backtest
  # performance analysis in order to generate initial data.
  workflow_dispatch:

permissions: {}

concurrency:
  group: ${{ github.workflow_ref }}-${{ github.ref_name != github.event.repository.default_branch && github.ref || github.run_id }}
  cancel-in-progress: true

jobs:
  benchmarks:
    name: Test
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout repository
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false

      - name: Setup Rust toolchain and cache
        uses: moonrepo/setup-rust@abb2d32350334249b178c401e5ec5836e0cd88d3 # v1.3.0
        with:
          channel: stable
          cache-target: release

      - name: Check
        run: cargo check

      - name: Shear
        run: cargo shear
        if: ${{ !cancelled() }}

      - name: Test
        run: cargo test
        if: ${{ !cancelled() }}
